spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: dearmoment
  profiles:
    default: local
  mail:
    host: smtp.gmail.com
    port: 587
    receiver: ${MAIL_RECEIVER}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
  oauth:
    kakao:
      client-id: ${OAUTH_KAKAO_CLIENT_ID}
      redirect-uri: ${OAUTH_KAKAO_REDIRECT_URI_LOCAL}

springdoc:
  packages-to-scan:
    - kr.kro.dearmoment  # 스캔할 패키지를 지정하세요.
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    enabled: true
    path: /v3/swagger  # swagger-ui 경로
  api-docs:
    path: /v3/api-docs  # JSON charset을 포함한 엔드포인트로 사용하려면 이처럼 설정합니다.

sentry:
  enabled: false