object-storage:
  bucket-name: ${OBJECT_STORAGE_BUCKET_NAME_LOCAL}
  config-path: ${OBJECT_STORAGE_CONFIG_PATH_LOCAL}
  namespace-name: ${OBJECT_STORAGE_NAMESPACE_NAME_LOCAL}
  photo-image-dir: ${OBJECT_STORAGE_IMAGE_DIR_LOCAL}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: demo
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect
  datasource:
    password:
    driver-class-name: oracle.jdbc.OracleDriver
    username: user
    url: jdbc:oracle:thin:@db:1521/FREEPDB1
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
  oauth:
    kakao:
      client-id: ${OAUTH_KAKAO_CLIENT_ID}
      redirect-uri: ${OAUTH_KAKAO_REDIRECT_URI}
      redirect:
        success: ${OAUTH_KAKAO_REDIRECT_SUCCESS}
        failure: ${OAUTH_KAKAO_REDIRECT_FAILURE}

springdoc:
  packages-to-scan:
    - kr.kro.dearmoment  # 스캔할 패키지를 지정하세요.
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    enabled: true
    path: /v3/swagger  # swagger-ui 경로
  api-docs:
    path: /v3/api-docs  # JSON charset을 포함한 엔드포인트로 사용하려면 이처럼 설정합니다.

