object-storage:
  bucket-name: ${OBJECT_STORAGE_BUCKET_NAME}
  config-path: ${OBJECT_STORAGE_CONFIG_PATH}
  namespace-name: ${OBJECT_STORAGE_NAMESPACE_NAME}
  photo-image-dir: ${OBJECT_STORAGE_IMAGE_DIR}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ${SPRING_APPLICATION_NAME}
  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}
  datasource:
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    url: ${SPRING_DATASOURCE_URL}
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
  oauth:
    kakao:
      client-id: ${OAUTH_KAKAO_CLIENT_ID}
      redirect-uri: ${OAUTH_KAKAO_REDIRECT_URI_PROD}

sentry:
  dsn: "${SENTRY_DSN}"
  exception-resolver-order: -2147483647
  max-request-body-size: always
  send-default-pii: true
  traces-sample-rate: 1.0

oracle:
  net:
    authentication_services: SSL
    ssl_version: "1.2"
    ssl_server_dn_match: true

springdoc:
  packages-to-scan:
    - kr.kro.dearmoment  # 스캔할 패키지를 지정하세요.
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    enabled: true
    path: /v3/swagger  # swagger-ui 경로
  api-docs:
    path: /v3/api-docs  # JSON charset을 포함한 엔드포인트로 사용하려면 이처럼 설정합니다.
